#!/bin/bash

export GURUBASH=$(cd $(dirname -- "$0") && pwd)
OS=$(bash ${GURUBASH}/pkg-manager/get-os.sh)

for loader in ${GURUBASH}/*/loader; do
    . ${loader}
done

for loader in ${GURUBASH}/*/loader.$OS; do
    . ${loader}
done

for bins in ${GURUBASH}/*/bins; do
    export PATH=${PATH}:${bins}
done

for bins in ${GURUBASH}/*/bins/$OS; do
    export PATH=${PATH}:${bins}
done
