alias spack='dpkg-buildpackage -rfakeroot -uc -us -sa -tc -D -I.git'
alias pack='git-buildpackage -rfakeroot -uc -us -sa -tc -D --git-tag --git-ignore-new'
alias srcobs='dpkg-buildpackage -rfakeroot -uc -us -sa -tc -D -S -I.git'
alias dput='dput -u'
alias ls='ls -h --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -hl'
alias la='ls -hA'
alias l='ls -hCF'
alias dch='dch --no-auto-nmu'
alias pylint='pylint -f colorized -i y -r n '
alias z='cd ..'
alias zz='cd ../..'
alias zzz='cd ../../..'
alias giff='git diff --cached'
#Add python application's parent dir to PYTHONPATH
alias pa='filepath=`pwd`;export PYTHONPATH=$PYTHONPATH:${filepath%/*}'
alias gtag='git-buildpackage --git-tag-only -d'
alias up='sudo apt-get update; sudo apt-get upgrade'
alias in='sudo apt-get install'
alias re='sudo apt-get remove'
alias py='python'
alias ssh='ssh -A' # fewer passwords
alias cl='git clean -fdx'
alias android-connect="mtpfs -o allow_other /media/GalaxyNexus"
alias android-disconnect="fusermount -u /media/GalaxyNexus"
alias pep8="pep8 --max-line-length=120"

function col {
    first="awk '{print "
    last="}'"
    cmd="${first}\$${1}${last}"
    eval $cmd
}

