# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Make bash autocomplete with up arrow from bash history
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

# Color definitions
black="\e[0;30m"
BLACK="\e[1;30m"
red="\e[0;31m"
RED="\e[1;31m"
green="\e[0;32m"
GREEN="\e[1;32m"
yellow="\e[0;33m"
YELLOW="\e[1;33m"
blue="\e[0;34m"
BLUE="\e[1;34m"
purple="\e[0;35m"
PURPLE="\e[1;35m"
cyan="\e[0;36m"
CYAN="\e[1;36m"
white="\e[0;37m"
WHITE="\e[1;37m"

username=`eval whoami`
if [ "$username" == "root" ];then
  usercolor=$GREEN
else
  usercolor=$YELLOW
fi

# Add to the end of the ~/.basrc file
# Colors the terminal in a nice way and shows git branch in a prompt all the time
# Adds some additional information to terminal

function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

# Wrapper for several parser - add hg and svn support in the future
function branch {
  a=`parse_git_branch`
  if [ -n "$a" ]; then
    echo -e "$BLUE[$CYAN$a$BLUE]"
  else
    echo ""
  fi
}

# Configure terminal colors
PS1="\[$BLUE\][\[$YELLOW\]\$(date +%H:%M)\[$BLUE\]]\
\[$BLUE\][\[$usercolor\]\u\[$RED\]@\[$YELLOW\]\h\[$BLUE\]][\[$YELLOW\]\w\[$BLUE\]]\
\$(branch)\
\n\
\[$WHITE\] > "
PS2='> '
PS4='+ '

# Add home bin directory if it exists to the path
DIR=$HOME/bin
if [ -d "$DIR" ]; then
    export PATH=$PATH:$DIR
fi

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Envireonment variables' definitons
if [ -f ~/.bash_env ]; then
    . ~/.bash_env
fi

# Bash cridentials
if [ -f ~/.bash_cridentials ]; then
    . ~/.bash_cridentials
fi
