#!/bin/bash

DEFAULT_THEME=dual-line.blue
DEFAULT_SHAPE=multiline

. ${GURUBASH}/theming/util_functions
. ${GURUBASH}/theming/bash_color_definitions
. ${GURUBASH}/theming/themes/${BASH_THEME:-${DEFAULT_THEME}}
. ${GURUBASH}/theming/shapes/${BASH_SHAPE:-${DEFAULT_SHAPE}}
