#!/bin/bash
function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

# Colors the terminal in a nice way and shows git branch in a prompt all the time
function branch {
  a=`parse_git_branch`
  if [ -n "${a}" ]; then
    echo -e "${cbracket}[${cbranch}${a}${cbracket}]"
  else
    echo ""
  fi
}

function aws_assumed_role {
  if [ -z "${AWS_ASSUMED_ROLE}" ]; then
    echo ""
  else
    echo -e "${cdog} ?? ${crole}${AWS_ASSUMED_ROLE}${Color_Off}"
  fi
}

# Show surprise smile if command returned error exit code
function surprise {
  status=$?
  if [ ${status} != 0 ]; then
    echo -e "${cstatus} O_O ${carrow}->${cstatus} ${status} \n${Color_Off}"
  else
    echo ""
  fi
}
